server:
  port: ${PORT:8080}
  url: https://currency-graphql.herokuapp.com
spring:
  datasource:
    url: jdbc:${CLEARDB_DATABASE_URL:postgresql://localhost:5432/converter}
    username: postgres
    password: root
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
      dialect: org.hibernate.dialect.PostgreSQLDialect