CREATE TABLE currencies
(
    id        VARCHAR(255) NOT NULL,
    num_code  VARCHAR(255),
    char_code VARCHAR(255),
    nominal   INTEGER,
    name      VARCHAR(255),
    CONSTRAINT pk_currencies PRIMARY KEY (id)
);

CREATE TABLE currency_rates
(
    id        VARCHAR(255) NOT NULL,
    date      date,
    char_code VARCHAR(255),
    rate      DOUBLE PRECISION,
    CONSTRAINT pk_currency_rates PRIMARY KEY (id)
);
CREATE TABLE conversions
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    first_currency  VARCHAR(255),
    second_currency VARCHAR(255),
    first_value     DOUBLE PRECISION,
    second_value    DOUBLE PRECISION,
    first_rate      DOUBLE PRECISION,
    second_rate     DOUBLE PRECISION,
    date            date,
    CONSTRAINT pk_conversions PRIMARY KEY (id)
);